	/* Power Button */

$(document).ready(function() {
	$(".Power_Button").click(function() {
		$(".Blackscreen").fadeToggle(900);
		});
	});

             /* YouTube App Opened */

$(document).ready(function() {
	$(".Phone_app_YouTube").click(function() {
		$(".Phone_App_Youtube_Opened").show(900),
		$(".Youtube_Logo").fadeIn(900),
		$(".ITGEN_IO_YT_Channel").fadeIn(900),
		$(".ITGEN_IO_YT_Channel_Description").fadeIn(900),
		$("a").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Phone_App_Youtube_Opened").hide(900),
		$(".Youtube_Logo").fadeOut(900),
		$(".ITGEN_IO_YT_Channel").fadeOut(900),
		$(".ITGEN_IO_YT_Channel_Description").fadeOut(900),
		$("a").fadeOut(100);
		});
	});

             /* Phone App Opened */

$(document).ready(function() {
	$(".phone_app_phone").click(function() {
		$(".Phone_App_Phone_Opened").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Phone_App_Phone_Opened").hide(900);
		});
	});

             /* Google play store app opened Games */

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Phone_App_PlayStore_Opened").show(900),
		$(".Green_thing_Playstore").show(900),
		$(".Fake_SearchBar_Playstore").show(900),
		$(".Real_SearchBar_Playstore").show(900),
		$(".Playstore_menu_button").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Phone_App_PlayStore_Opened").hide(900),
		$(".Green_thing_Playstore").hide(900),
		$(".Fake_SearchBar_Playstore").hide(900),
		$(".Real_SearchBar_Playstore").hide(900),
		$(".Playstore_menu_button").hide(900);
		});
	});

		/* Playstore Games */

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Playstore_word_Games").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Playstore_word_Games").hide(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Playstore_word_Apps").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Playstore_word_Apps").hide(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Playstore_word_Music").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Playstore_word_Music").hide(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".SnakeGame_Playstore").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".SnakeGame_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".SnakeGame_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".SnakeGame_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".SnakeGame_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Word_Snake_Playstore").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Snake_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Snake_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Snake_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Snake_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Game_Border_Playstore").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Game_Border_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Game_Border_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Game_Border_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Game_Border_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Fortnite_Add_Playstore").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Fortnite_Add_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Fortnite_Add_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Fortnite_Add_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Fortnite_Add_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Word_Games").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Games").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Games").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Games").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Games").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Tic_Tac_Toe_Game_Playstore").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Tic_Tac_Toe_Game_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Tic_Tac_Toe_Game_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Tic_Tac_Toe_Game_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Tic_Tac_Toe_Game_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Word_Tic_Tac_Toe_Playstore").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Tic_Tac_Toe_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Tic_Tac_Toe_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Tic_Tac_Toe_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Tic_Tac_Toe_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Treasure_Hunt_Game_Playstore").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Treasure_Hunt_Game_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Treasure_Hunt_Game_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Treasure_Hunt_Game_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Treasure_Hunt_Game_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Word_Treasure").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Treasure").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Treasure").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Treasure").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Treasure").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Word_Hunt").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Hunt").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Hunt").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Hunt").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Hunt").fadeIn(900);
		});
	});

			/* Playstore Music */

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Music_Apps_Border_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Music_Apps_Border_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Music_Apps_Border_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Music_Apps_Border_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Samsung_Music_App_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Samsung_Music_App_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Samsung_Music_App_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Samsung_Music_App_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Music").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Music").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Music").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Music").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Samsung_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Samsung_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Samsung_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Samsung_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Music_SamsungMusic_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Music_SamsungMusic_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Music_SamsungMusic_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Music_SamsungMusic_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Google_Music_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Google_Music_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Google_Music_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Google_Music_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Google_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Google_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Google_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Google_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_PlayMusic_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_PlayMusic_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_PlayMusic_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_PlayMusic_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".SoundCloud_IMG_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".SoundCloud_IMG_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".SoundCloud_IMG_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".SoundCloud_IMG_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_SoundCloud").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_SoundCloud").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_SoundCloud").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_SoundCloud").hide(900);
		});
	});

		/* Apps on Google play store */

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Google_Maps_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Google_Maps_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Google_Maps_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Google_Maps_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Apps_Border_Apps_playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Apps_Border_Apps_playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Apps_Border_Apps_playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Apps_Border_Apps_playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Google_GoogleMaps_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Google_GoogleMaps_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Google_GoogleMaps_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Google_GoogleMaps_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Maps_GoogleMaps_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Maps_GoogleMaps_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Maps_GoogleMaps_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Maps_GoogleMaps_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Apps_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Apps_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Apps_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Apps_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Viber_Icon_Playstore").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Viber_Icon_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Viber_Icon_Playstore").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Viber_Icon_Playstore").hide(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Apps").click(function() {
		$(".Word_Viber").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Games").click(function() {
		$(".Word_Viber").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Playstore_word_Music").click(function() {
		$(".Word_Viber").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Word_Viber").hide(900);
		});
	});

			/* Messeges app opened */

$(document).ready(function() {
	$(".phone_app_Messages").click(function() {
		$(".Phone_App_Messeges_Opened").show(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Phone_App_Messeges_Opened").hide(900);
		});
	});

			/* Notifacation bar */

$(document).ready(function() {
	$(".phone_app_Messages").click(function() {
		$(".Notiphacations_bar").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_GooglePlayStore").click(function() {
		$(".Notiphacations_bar").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_app_phone").click(function() {
		$(".Notiphacations_bar").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Phone_app_YouTube").click(function() {
		$(".Notiphacations_bar").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".Home_Button").click(function() {
		$(".Notiphacations_bar").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".invis_Notiphacations_bar").click(function() {
		$(".Notifacation_bar_opened").slideToggle(900);
		$(".fab fa-bluetooth-b").slideToggle(900);
		$(".fas fa-wifi").slideToggle(900);
		$(".fas fa-volume-up").slideToggle(900);
		$(".fas fa-plane").slideToggle(900);
		$(".fas fa-phone").slideToggle(900);
		});
	});


			/* If background 1 Picked is clicked*/

$(document).ready(function() {
	$(".phone_background_1_picked").click(function() {
		$(".phone_background_1_pick").fadeIn(900),
		$(".phone_background_2_pick").fadeIn(900),
		$(".phone_background_3_pick").fadeIn(900),
		$(".phone_background_4_pick").fadeIn(900),
		$(".phone_background_5_pick").fadeIn(900),
		$(".phone_background_6_pick").fadeIn(900);
		});
	});
		// If background 1 is picked then... 

$(document).ready(function() {
	$(".phone_background_1_pick").click(function() {
		$(".phone_background_1_picked").fadeIn(900),
		$(".phone_background_2_picked").fadeOut(900),
		$(".phone_background_3_picked").fadeOut(900),
		$(".phone_background_4_picked").fadeOut(900),
		$(".phone_background_5_picked").fadeOut(900),
		$(".phone_background_6_picked").fadeOut(900),
		$(".phone_background_1_pick").fadeOut(900),
		$(".phone_background_2_pick").fadeOut(900),
		$(".phone_background_3_pick").fadeOut(900),
		$(".phone_background_4_pick").fadeOut(900),
		$(".phone_background_5_pick").fadeOut(900),
		$(".phone_background_6_pick").fadeOut(900);
		});
	});

			/* If background 2 Picked is clicked*/

$(document).ready(function() {
	$(".phone_background_2_picked").click(function() {
		$(".phone_background_1_pick").fadeIn(900),
		$(".phone_background_2_pick").fadeIn(900),
		$(".phone_background_3_pick").fadeIn(900),
		$(".phone_background_4_pick").fadeIn(900),
		$(".phone_background_5_pick").fadeIn(900),
		$(".phone_background_6_pick").fadeIn(900);
		});
	});

		// If background 2 is picked then... 

$(document).ready(function() {
	$(".phone_background_2_pick").click(function() {
		$(".phone_background_1_picked").fadeOut(900),
		$(".phone_background_2_picked").fadeIn(900),
		$(".phone_background_3_picked").fadeOut(900),
		$(".phone_background_4_picked").fadeOut(900),
		$(".phone_background_5_picked").fadeOut(900),
		$(".phone_background_6_picked").fadeOut(900);
		$(".phone_background_1_pick").fadeOut(900);
		$(".phone_background_2_pick").fadeOut(900);
		$(".phone_background_3_pick").fadeOut(900);
		$(".phone_background_4_pick").fadeOut(900);
		$(".phone_background_5_pick").fadeOut(900);
		$(".phone_background_6_pick").fadeOut(900);
		});
	});	


			/* If background 3 Picked is clicked*/

$(document).ready(function() {
	$(".phone_background_3_picked").click(function() {
		$(".phone_background_1_pick").fadeIn(900);
		$(".phone_background_2_pick").fadeIn(900);
		$(".phone_background_3_pick").fadeIn(900);
		$(".phone_background_4_pick").fadeIn(900);
		$(".phone_background_5_pick").fadeIn(900);
		$(".phone_background_6_pick").fadeIn(900);
		});
	});

		// If background 3 is picked then... 

$(document).ready(function() {
	$(".phone_background_3_pick").click(function() {
		$(".phone_background_1_picked").fadeOut(900),
		$(".phone_background_2_picked").fadeOut(900),
		$(".phone_background_3_picked").fadeIn(900),
		$(".phone_background_4_picked").fadeOut(900),
		$(".phone_background_5_picked").fadeOut(900),
		$(".phone_background_6_picked").fadeOut(900),
		$(".phone_background_1_pick").fadeOut(900),
		$(".phone_background_2_pick").fadeOut(900),
		$(".phone_background_3_pick").fadeOut(900),
		$(".phone_background_4_pick").fadeOut(900),
		$(".phone_background_5_pick").fadeOut(900),
		$(".phone_background_6_pick").fadeOut(900);

		});
	});		

			/* If background 4 Picked is clicked*/

$(document).ready(function() {
	$(".phone_background_4_picked").click(function() {
		$(".phone_background_1_pick").fadeIn(900),
		$(".phone_background_2_pick").fadeIn(900),
		$(".phone_background_3_pick").fadeIn(900),
		$(".phone_background_4_pick").fadeIn(900),
		$(".phone_background_5_pick").fadeIn(900),
		$(".phone_background_6_pick").fadeIn(900);
		});
	});

		// If background 4 is picked then... 

$(document).ready(function() {
	$(".phone_background_4_pick").click(function() {
		$(".phone_background_1_picked").fadeOut(900),
		$(".phone_background_2_picked").fadeOut(900),
		$(".phone_background_3_picked").fadeOut(900),
		$(".phone_background_4_picked").fadeIn(900),
		$(".phone_background_5_picked").fadeOut(900),
		$(".phone_background_6_picked").fadeOut(900),
		$(".phone_background_1_pick").fadeOut(900),
		$(".phone_background_2_pick").fadeOut(900),
		$(".phone_background_3_pick").fadeOut(900),
		$(".phone_background_4_pick").fadeOut(900),
		$(".phone_background_5_pick").fadeOut(900),
		$(".phone_background_6_pick").fadeOut(900);
		});
	});	

			/* If background 5 Picked is clicked*/

$(document).ready(function() {
	$(".phone_background_5_picked").click(function() {
		$(".phone_background_1_pick").fadeIn(900),
		$(".phone_background_2_pick").fadeIn(900),
		$(".phone_background_3_pick").fadeIn(900),
		$(".phone_background_4_pick").fadeIn(900),
		$(".phone_background_5_pick").fadeIn(900),
		$(".phone_background_6_pick").fadeIn(900);
		});
	});
		// If background 5 is picked then... 

$(document).ready(function() {
	$(".phone_background_5_pick").click(function() {
		$(".phone_background_1_picked").fadeOut(900),
		$(".phone_background_2_picked").fadeOut(900),
		$(".phone_background_3_picked").fadeOut(900),
		$(".phone_background_4_picked").fadeOut(900),
		$(".phone_background_5_picked").fadeIn(900),
		$(".phone_background_6_picked").fadeOut(900),
		$(".phone_background_1_pick").fadeOut(900),
		$(".phone_background_2_pick").fadeOut(900),
		$(".phone_background_3_pick").fadeOut(900),
		$(".phone_background_4_pick").fadeOut(900),
		$(".phone_background_5_pick").fadeOut(900),
		$(".phone_background_6_pick").fadeOut(900);
		});
	});	

			/* If background 6 Picked is clicked*/

$(document).ready(function() {
	$(".phone_background_6_picked").click(function() {
		$(".phone_background_1_pick").fadeIn(900),
		$(".phone_background_2_pick").fadeIn(900),
		$(".phone_background_3_pick").fadeIn(900),
		$(".phone_background_4_pick").fadeIn(900),
		$(".phone_background_5_pick").fadeIn(900),
		$(".phone_background_6_pick").fadeIn(900);
		});
	});

		// If background 6 is picked then... 



$(document).ready(function() {
	$(".phone_background_6_pick").click(function() {
		$(".phone_background_1_picked").fadeOut(900),
		$(".phone_background_2_picked").fadeOut(900),
		$(".phone_background_3_picked").fadeOut(900),
		$(".phone_background_4_picked").fadeOut(900),
		$(".phone_background_5_picked").fadeOut(900),
		$(".Change_background_input").fadeIn(900),
		$(".Change_background_input_detail").fadeIn(900),
		$(".Change_background_button").fadeIn(900);
		});
	});	


$(document).ready(function() {
	$(".Change_background_button").click(function() {
		$(".phone_background_1_pick").fadeOut(900),
		$(".phone_background_2_pick").fadeOut(900),
		$(".phone_background_3_pick").fadeOut(900),
		$(".phone_background_4_pick").fadeOut(900),
		$(".phone_background_5_pick").fadeOut(900),
		$(".phone_background_6_pick").fadeOut(900),
		$("Change_background_button").fadeOut(900),
		$("Change_background_input").fadeOut(900),
		$("Change_background_input_detail").fadeOut(900),
		$(".phone_background_6_picked").fadeIn(900);
		});
	});		



		// fade effect

$(document).ready(function() {
	$(".phone_background_1_picked").click(function() {
		$(".fade_effect").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_background_2_picked").click(function() {
		$(".fade_effect").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_background_3_picked").click(function() {
		$(".fade_effect").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_background_4_picked").click(function() {
		$(".fade_effect").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_background_5_picked").click(function() {
		$(".fade_effect").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_background_6_picked").click(function() {
		$(".fade_effect").fadeIn(900);
		});
	});

$(document).ready(function() {
	$(".phone_background_1_pick").click(function() {
		$(".fade_effect").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".phone_background_2_pick").click(function() {
		$(".fade_effect").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".phone_background_3_pick").click(function() {
		$(".fade_effect").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".phone_background_4_pick").click(function() {
		$(".fade_effect").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".phone_background_5_pick").click(function() {
		$(".fade_effect").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".Change_background_button").click(function() {
		$(".fade_effect").fadeOut(900);
		});
	});

$(document).ready(function() {
	$(".invis_Notiphacations_bar").click(function() {
		$(".fade_effect").fadeToggle(900);
		});
	});





		// Coding

/*function gotosearch(){

var search = document.getElementById('SearchBar').value; 
window.location = "http://www.google.com.pk/#hl=en&source=hp&biw=1024&bih=604&q="+search+"&aq=f&aqi=&aql=&oq=&gs_rfai=&fp=1";
return true;
}

*/

		/* Change background */ 

/*function ImageSearch() {

var linImg = document.getElementById("Change_background_input").value;

alert(linImg);


}*/
